apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-h2hh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-h2hh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-h2hh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-h2hh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-h2hh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iazr-tenant/rhtap-demo-app/hacbs-test-project-h2hh@sha256:430e9ed63a3982edd63a2f320f7e07867525717cc6edcab573c3a460fb6f54b1
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
